# GoReleaser v2 configuration
version: 2

project_name: super
builds:
  - main: ./cmd/super
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -X github.com/brimdata/super/cli.version=v0.0.0-{{ replace (replace (replace (replace .CommitDate "-" "") ":" "") "T" "") "Z" "" }}-{{ .ShortCommit }}'
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ "zip" ]
    files:
      - LICENSE.txt
      - acknowledgments.txt
release:
  header: |
    View [change log](CHANGELOG.md#{{ replace .Tag "." "" }}).
homebrew_casks:
  - repository:
      owner: brimdata
      name: homebrew-tap
    commit_author:
      name: brim-bot
      email: bot@brimdata.io
    homepage: https://github.com/brimdata/super
    description: |
      An analytics database that fuses structured and semi-structured data
    url:
      template: "https://super-prereleases.s3.us-east-2.amazonaws.com/{{ .Version }}/{{ .ArtifactName }}"
checksum:
  name_template: 'super-checksums.txt'
snapshot:
  version_template: 'v0.0.0-{{ replace (replace (replace (replace .CommitDate "-" "") ":" "") "T" "") "Z" "" }}-{{ .ShortCommit }}'
changelog:
  disable: true
