# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zed < Formula
  desc "A command-line tool for creating, configuring, ingesting into, querying,
and orchestrating Zed data lakes.
"
  homepage "https://github.com/brimdata/zed"
  version "1.11.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brimdata/zed/releases/download/v1.11.0/zed-v1.11.0.darwin-arm64.tar.gz"
      sha256 "03f476397bc5d539fe3e2e4b8ba6b6e3ac36deefb2480c2a462294de76a25feb"

      def install
        bin.install "zed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.11.0/zed-v1.11.0.darwin-amd64.tar.gz"
      sha256 "882a4dcc8b5080ef0861d3ad8a16120b8c23fc3f432a19eb8992f11cf7964cc1"

      def install
        bin.install "zed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brimdata/zed/releases/download/v1.11.0/zed-v1.11.0.linux-arm64.tar.gz"
      sha256 "d86c525892d0f5541f69e2096234451b4d6df36fcaa9081871425b85580a30b2"

      def install
        bin.install "zed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.11.0/zed-v1.11.0.linux-amd64.tar.gz"
      sha256 "2722c57a4a0f9a31e3018761fa848ed63a33ad6e95c041396be17f3b6aefd248"

      def install
        bin.install "zed"
      end
    end
  end
end
