# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zed < Formula
  desc "A command-line tool for creating, configuring, ingesting into, querying,
and orchestrating Zed data lakes.
"
  homepage "https://github.com/brimdata/zed"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brimdata/zed/releases/download/v1.8.0/zed-v1.8.0.darwin-arm64.tar.gz"
      sha256 "21d468c1a79bf711172c74cc6f72c12365f74ccf3dfd5ac7f8b23d7c20f536d7"

      def install
        bin.install "zed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.8.0/zed-v1.8.0.darwin-amd64.tar.gz"
      sha256 "a162f0be131ab03c7bf4d74b197a0c374da8a6549c34db9402481261f703430e"

      def install
        bin.install "zed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brimdata/zed/releases/download/v1.8.0/zed-v1.8.0.linux-arm64.tar.gz"
      sha256 "0bf6ed7adaa5828379d2284900d59fb5b42cd7fb96c791be3b410cf46b25134f"

      def install
        bin.install "zed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.8.0/zed-v1.8.0.linux-amd64.tar.gz"
      sha256 "c9246e7075e31c2aed412f89a0c6b25ecd6e6da59bd46c079f5f64e43f58024c"

      def install
        bin.install "zed"
      end
    end
  end
end
