# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zed < Formula
  desc "A command-line tool for creating, configuring, ingesting into, querying,
and orchestrating Zed data lakes.
"
  homepage "https://github.com/brimdata/zed"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brimdata/zed/releases/download/v1.4.0/zed-v1.4.0.darwin-arm64.tar.gz"
      sha256 "6320a20bed4b2bfd170de0beeafc3b33d7818eb5f0825ebaccec8697cd0233aa"

      def install
        bin.install "zed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.4.0/zed-v1.4.0.darwin-amd64.tar.gz"
      sha256 "7fdf2b3501d47b5675b1ccbb562ad132ea9b1379cab30ff1b5d014d4f20dbca5"

      def install
        bin.install "zed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brimdata/zed/releases/download/v1.4.0/zed-v1.4.0.linux-arm64.tar.gz"
      sha256 "fe1df843588d0f14789822f8217bbee639113857c7cf82a718e79f28723eb754"

      def install
        bin.install "zed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.4.0/zed-v1.4.0.linux-amd64.tar.gz"
      sha256 "4ae49399f26defe97bd042c20c087ff9c2093843bcd993bba0221228b0216190"

      def install
        bin.install "zed"
      end
    end
  end
end
