# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zq < Formula
  desc "A command-line tool for processing data in diverse input formats,
providing search, analytics, and extensive transormations using the Zed
query language.
"
  homepage "https://github.com/brimdata/zed"
  version "1.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.10.0/zed-v1.10.0.darwin-amd64.tar.gz"
      sha256 "09c618606a444ee05d84d773fc4cb32968873abbeb8cad22bfe01046a4aef360"

      def install
        bin.install "zq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brimdata/zed/releases/download/v1.10.0/zed-v1.10.0.darwin-arm64.tar.gz"
      sha256 "3bba4a03bd3629c2ad230a30a7f44e9d2f91d64870aa6d7f9bec6b0ed2419002"

      def install
        bin.install "zq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.10.0/zed-v1.10.0.linux-amd64.tar.gz"
      sha256 "fd807e77e4b918d5c43a94e0833d1496b47f54548797978253b162be8c6f1aba"

      def install
        bin.install "zq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brimdata/zed/releases/download/v1.10.0/zed-v1.10.0.linux-arm64.tar.gz"
      sha256 "297be19d23805f012c7b186790b91b856efd7f7f56d381f0452c2983b681d124"

      def install
        bin.install "zq"
      end
    end
  end
end
