# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zq < Formula
  desc "A command-line tool for processing data in diverse input formats,
providing search, analytics, and extensive transormations using the Zed
query language.
"
  homepage "https://github.com/brimdata/zed"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brimdata/zed/releases/download/v1.3.0/zed-v1.3.0.darwin-arm64.tar.gz"
      sha256 "834770f9f859d4e8ba73db028ffe84a455eca50eb6206e67034778df73087207"

      def install
        bin.install "zq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.3.0/zed-v1.3.0.darwin-amd64.tar.gz"
      sha256 "a361a11f296d326038df1c3cbbb31dbb665aeaabe345b3397ee975314410ce79"

      def install
        bin.install "zq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brimdata/zed/releases/download/v1.3.0/zed-v1.3.0.linux-amd64.tar.gz"
      sha256 "1a6d89a26d78ac3405bfca4ebd35087851b29c2be3f5708e52f4200d3f89a7f4"

      def install
        bin.install "zq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brimdata/zed/releases/download/v1.3.0/zed-v1.3.0.linux-arm64.tar.gz"
      sha256 "3a6a152063f053fc4d8ed6b8c79e3d804eb8b5e330974506f1ff1380b80632e0"

      def install
        bin.install "zq"
      end
    end
  end
end
