# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zync < Formula
  desc "Kafka connector to sync Zed lakes to and from Kafka topics
"
  homepage "https://github.com/brimdata/zync"
  version "0.11.0"

  on_macos do
    on_intel do
      url "https://github.com/brimdata/zync/releases/download/v0.11.0/zync-v0.11.0.darwin-amd64.tar.gz"
      sha256 "fef1e284718efb2b7e2af64671ecc27a9e7ea25d8027df2ff3522fb7b124d79a"

      def install
        bin.install "zync"
      end
    end
    on_arm do
      url "https://github.com/brimdata/zync/releases/download/v0.11.0/zync-v0.11.0.darwin-arm64.tar.gz"
      sha256 "17d031a4762de69d3ff0b75e5e020d85d4a2b1a7d756cbedd03cb3f47a0e8089"

      def install
        bin.install "zync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brimdata/zync/releases/download/v0.11.0/zync-v0.11.0.linux-amd64.tar.gz"
        sha256 "e513531021133b167bbad5ec6df02d9376e691252c4362a4f24b217a54d0d517"

        def install
          bin.install "zync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brimdata/zync/releases/download/v0.11.0/zync-v0.11.0.linux-arm64.tar.gz"
        sha256 "0f50c6b7264f7b3ae7d33b7f548cf593abf4d8b7b842dd1c789cd28c1c1a751c"

        def install
          bin.install "zync"
        end
      end
    end
  end
end
