# This file was generated by GoReleaser. DO NOT EDIT.
cask "super" do
  name "super"
  desc "An analytics database that fuses structured and semi-structured data
"
  homepage "https://github.com/brimdata/super"
  version "8ebde76"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "super"

  on_macos do
    on_intel do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.darwin-amd64.tar.gz"
      sha256 "1e951ea9e193273bee3e82572d4d6dc2a4f5a1a20cbce2d1aa4d2ca0e694f013"
    end
    on_arm do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.darwin-arm64.tar.gz"
      sha256 "438381e8de197eccee2b0fc2c8cbc742d31bea09611f83b4618ccb881db8a397"
    end
  end

  on_linux do
    on_intel do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.linux-amd64.tar.gz"
      sha256 "c814fa5a7eaa5912c0cba4d214f7b13a8afbf79937401bdddd986def62ff60f8"
    end
    on_arm do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.linux-arm64.tar.gz"
      sha256 "c968e86258fdc19d68a5e27bb801087637614880a42a0cde75205dfff0383cf5"
    end
  end

  # No zap stanza required
end
