# This file was generated by GoReleaser. DO NOT EDIT.
cask "super" do
  name "super"
  desc "An analytics database that fuses structured and semi-structured data
"
  homepage "https://github.com/brimdata/super"
  version "cad1342"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "super"

  on_macos do
    on_intel do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.darwin-amd64.tar.gz"
      sha256 "d1bb6648bb0850e2b3c32b8a5c29a422dc4583f21a5f368f160cab2a856d16be"
    end
    on_arm do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.darwin-arm64.tar.gz"
      sha256 "b23c2bbc2f00629efc14d6044fbd4925e6ac2cf9c3f2f012ee01d9806ef94eac"
    end
  end

  on_linux do
    on_intel do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.linux-amd64.tar.gz"
      sha256 "711bd2e765969fd42b0778f9f5160e6659c005fb055a1566a1ee99d73831305b"
    end
    on_arm do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.linux-arm64.tar.gz"
      sha256 "aa4e45f180b37ec06d76ba5df7d216d4e362958dd2f83e2d23595c3e5ff3414f"
    end
  end

  # No zap stanza required
end
