name: "Update SuperDB Homebrew Cask"

on:
  schedule:
    - cron: '5 8 * * *'
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Checkout super
        uses: actions/checkout@v4
        with:
          repository: brimdata/super
          path: super
      - name: Check if super main has changed
        id: changed
        run: |
          ( [ ! -f Casks/super.rb ] || [ $(awk '/version/ {print $2}' Casks/super.rb | head -1 | tr -d '"') != $(git -C super rev-parse --short HEAD | cut -c1-7) ] ) && echo "changed=true" >> $GITHUB_OUTPUT || true
      - uses: actions/setup-go@v5
        with:
          go-version-file: super/go.mod
          cache-dependency-path: super/go.sum
      - name: Build new artifacts if super changed since last run
        if: steps.changed.outputs.changed == 'true'
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir: super
          args: release --config=${{ github.workspace }}/.super-prerelease-cask-goreleaser.yaml --snapshot --clean
      - uses: aws-actions/configure-aws-credentials@v5
        if: steps.changed.outputs.changed == 'true'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Upload artifacts to S3 bucket
        if: steps.changed.outputs.changed == 'true'
        run: |
          short_hash=$(git -C super rev-parse --short HEAD)
          for artifact in super/dist/super-${short_hash}*; do aws s3 cp $artifact s3://super-prereleases/${short_hash}/ ; done
      - name: Save updated Cask to Homebrew tap repo
        if: steps.changed.outputs.changed == 'true'
        run: |
          mkdir -p Casks
          cp super/dist/homebrew/Casks/super.rb Casks
          git config --global user.name 'Brim Automation'
          git config --global user.email 'automation@brimdata.com'
          git add Casks/super.rb
          git commit -am "update super Homebrew Cask to $(git -C super rev-parse --short HEAD)" || true
          git push
